# Generated by Django 3.0.2 on 2020-01-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Members',
        ),
    ]
